# User Configuration for ${keyboard.name}

# Configuración de Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Reduce el lag de entrada para que el mod-tap se sienta instantáneo
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# --- ISSUES CONNECTING TO WINDOWS ---
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

# --- MOUSE KEYS ---
# Habilitar soporte de Ratón
CONFIG_ZMK_MOUSE=y

# Aumenta la velocidad de respuesta de la conexión (Polling rate)
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=1
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=2

# --- ZMK STUDIO ---
# Si vas a usar ZMK Studio, asegúrate de que esta línea esté presente:
CONFIG_ZMK_STUDIO=y
