# User Configuration for ${keyboard.name}

# Configuración de Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Reduce el lag de entrada para que el mod-tap se sienta instantáneo
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# --- MOUSE KEYS ---
# Habilitar soporte de Ratón
CONFIG_ZMK_MOUSE=y

# --- ZMK STUDIO ---
# Si vas a usar ZMK Studio, asegúrate de que esta línea esté presente:
CONFIG_ZMK_STUDIO=y
