# User Configuration for ${keyboard.name}

# Configuración de Encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# --- MOUSE KEYS ---
# Habilitar soporte de Ratón
CONFIG_ZMK_MOUSE=y
# Velocidad máxima de los ejes (píxeles por paso)
CONFIG_ZMK_MOUSE_TICK_DURATION=8
CONFIG_ZMK_MOUSE_SPEED_MAX=600
# Tiempo que tarda en llegar a la velocidad máxima (ms)
CONFIG_ZMK_MOUSE_DELAY=0
CONFIG_ZMK_MOUSE_ACCEL_TIME=300

# --- ZMK STUDIO ---
# Si vas a usar ZMK Studio, asegúrate de que esta línea esté presente:
CONFIG_ZMK_STUDIO=y
